# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /blog/:title

# Setup
title:            Jeff Naecker
tagline:          In data we trust.
url:              http://jeffnaecker.com
paginate:         3
paginate_path: 	  "blog/page:num"
baseurl:          /
author:
  name:           Jeff Naecker
  url:            https://twitter.com/jnaecker
  email:          jnaecker@gmail.com

# Menu
pages_list:
  Research: '/research'
  Teaching: '/teaching'	
  Blog: '/blog'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
